; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
board_build.partitions = partitions_ota.csv
lib_deps = 
    esphome/ESPAsyncWebServer-esphome@^3.2.2
    esphome/AsyncTCP-esphome@^2.1.4
extra_scripts = extra_script.py
monitor_port = COM9
monitor_speed = 115200
monitor_filters = direct
monitor_rts = 0
monitor_dtr = 0

; OTA environment - upload wirelessly via OTA
[env:esp32cam_ota]
platform = espressif32
board = esp32cam
framework = arduino
board_build.partitions = partitions_ota.csv
lib_deps = 
    esphome/ESPAsyncWebServer-esphome@^3.2.2
    esphome/AsyncTCP-esphome@^2.1.4
extra_scripts = extra_script.py
upload_protocol = espota
upload_port = esp32-cam-4wd.local
upload_flags = 
    --auth=12345678
    --port=3232
monitor_port = COM9
monitor_speed = 115200
monitor_filters = direct
monitor_rts = 0
monitor_dtr = 0
